import { Node, Project, SyntaxKind, Type, TypeFormatFlags } from 'ts-morph'
import path from 'node:path'
import { AnalysisResult, Component } from './types.js'

export interface GenOptions {
  /** Emit augmentation entries for the module with this name. */
  moduleName?: string
}

export interface GenResult {
  /** The generated .d.ts text (empty when nothing needs generating). */
  augmentation: string
  /** Keys that were generated, with their inferred type text. */
  generated: { key: string; type: string; component: string }[]
  /** Keys skipped because a module augmentation already declares them. */
  skipped: string[]
}

/**
 * Generate the `declare module 'cordis' { interface Context { … } }`
 * augmentation for provisions that lack one, inferring each key's type
 * from the value passed to `ctx.set(key, value)` (or the Service subclass
 * instance type). The augmentation a provider hand-writes for type safety
 * is exactly the coeffect declaration `cordisc check` verifies — `gen`
 * writes it from the code instead.
 */
export function generate(project: Project, result: AnalysisResult, options: GenOptions = {}): GenResult {
  const moduleName = options.moduleName ?? 'cordis'
  const generated: GenResult['generated'] = []
  const skipped: string[] = []

  const contextType = probeContextType(project, moduleName)

  for (const component of result.components) {
    for (const key of component.provides) {
      if (contextType?.getProperty(key)) {
        skipped.push(key)
        continue
      }
      const type = inferProvisionType(component, key)
      generated.push({ key, type, component: component.name })
    }
  }

  if (!generated.length) return { augmentation: '', generated, skipped }

  const lines = [
    '// generated by cordisc gen — do not edit',
    `declare module '${moduleName}' {`,
    '  interface Context {',
    ...generated.map(({ key, type, component }) => `    /** provided by ${component} */\n    ${JSON.stringify(key).includes(' ') ? JSON.stringify(key) : key}: ${type}`),
    '  }',
    '}',
    'export {}',
    '',
  ]
  return { augmentation: lines.join('\n'), generated, skipped }
}

/** Resolve the augmented Context type via an in-memory probe file. */
export function probeContextType(project: Project, moduleName: string): Type | undefined {
  const probePath = path.join(project.getRootDirectories()[0]?.getPath() ?? process.cwd(), '__cordisc_probe.ts')
  try {
    const probe = project.createSourceFile(probePath,
      `import { Context } from '${moduleName}'\nexport declare const __cordisc_ctx: Context\n`,
      { overwrite: true })
    const type = probe.getVariableDeclarationOrThrow('__cordisc_ctx').getType()
    return type
  } catch {
    return undefined
  }
}

function inferProvisionType(component: Component, key: string): string {
  for (const body of component.bodies) {
    for (const call of body.getDescendantsOfKind(SyntaxKind.CallExpression)) {
      const callee = call.getExpression()
      if (!Node.isPropertyAccessExpression(callee)) continue
      if (!['set', 'provide'].includes(callee.getName())) continue
      const [keyArg, valueArg] = call.getArguments()
      if (!keyArg || !Node.isStringLiteral(keyArg) || keyArg.getLiteralText() !== key) continue
      if (!valueArg) continue
      const text = valueArg.getType().getText(valueArg,
        TypeFormatFlags.NoTruncation | TypeFormatFlags.UseAliasDefinedOutsideCurrentScope)
      if (text && text !== 'any') return text
    }
    // Service subclass: super(ctx, key) — the provision is the instance type
    for (const call of body.getDescendantsOfKind(SyntaxKind.CallExpression)) {
      if (call.getExpression().getKind() !== SyntaxKind.SuperKeyword) continue
      const nameArg = call.getArguments()[1]
      if (!nameArg || !Node.isStringLiteral(nameArg) || nameArg.getLiteralText() !== key) continue
      const cls = call.getFirstAncestorByKind(SyntaxKind.ClassDeclaration)
      const name = cls?.getName()
      if (name) return name
    }
  }
  return 'unknown'
}
